name: Build

on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master, dev]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-app.yml
    with:
      skip_flasher: true
      uv_sync_mode: "locked"
